disabled_rules:
  - trailing_whitespace
#   - function_body_length
#   - line_length
#   - orphaned_doc_comment
#   - nesting

# opt_in_rules:
#   - let_var_whitespace

included:
  - Happic-iOS
excluded:
  # AppDelegate, SceneDelegate file 무시
  - Happic-iOS/AppDelegate.swift
  - Happic-iOS/SceneDelegate.swift

# identifier_name:
#   excluded:
#     - id

# force_cast: warning